# 项目启用开关
Enabled : false

# 项目名称(每个项目必填 格式: 链-模式-币名字)
Name : "XX-Invoke-项目"

# SwapRouter
# Pancake  0x10ed43c718714eb63d5aa57b78b54704e256024e
# Pandaex  0x6eC2A127057c13Dff1D04e0ae131a756aa4033d4
# Cherry   0x865bfde337c8afbfff144ff4c29f9404ebb22b15
# KingSwap 0xca2af2a9b1ef83e5023fed514aa5a622cfaf8d4b
SwapRouter : "0x10ed43c718714eb63d5aa57b78b54704e256024e" 

# 模式 (调用监控模式)
Model : "Invoke"

# 调用者
Sender : "0xd5d3189cf80464877d41a79a22b6cff23bf0a722"
# 监控 被添加流动性的地址
# Contract : "0xe540980f909873370bbe9c19db7c3b5ba4def701"

AccountGroups :
  - "Main"

# 购买参数
Transaction :
  # 购买量
  Cost : 10
  # 购买循环次数
  Count : 1
  # 购买超时
  OutTime : 1000

#延迟购买
# Delay :
  # Time : 10
  # Block : 3

# 交易参数
Exact : 
  # 使用智能路由 (强制使用BNB去购买满足流动性检测的币)
  Send : "0x382bb369d343125bfb2117af9c149795c6c65c50"
  # 最低购买数量 (为0无视滑点)
  AmountOutMin : 100
  # gas价格 (不写则为跟踪模式)
  # GasPrice : 5
  # gas数量
  GasCount : 500000
  # 购买超时(秒)
  OutTime : 1000

# Invoke:
#   MethodID : "0x267dd102"