<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<LangVersion>preview</LangVersion>
		<TargetFramework>net5</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Config\AccountGroup\**" />
	  <Compile Remove="Config\Anti\**" />
	  <EmbeddedResource Remove="Config\AccountGroup\**" />
	  <EmbeddedResource Remove="Config\Anti\**" />
	  <None Remove="Config\AccountGroup\**" />
	  <None Remove="Config\Anti\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="config.yaml" />
		<None Remove="Config\Account\Main.yaml" />
		<None Remove="Config\Project\Invoke-Burning.yaml" />
		<None Remove="Config\Project\Invoke.yaml" />
		<None Remove="Config\Project\Swap-Burning.yaml" />
		<None Remove="Config\Project\Swap.yaml" />
		<None Remove="Config\Project\Transaction.yaml" />
		<None Remove="logSetting.yaml" />
	</ItemGroup>


	<ItemGroup>
		<EmbeddedResource Include="Config\config.yaml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Account\Main.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Project\Invoke-Burning.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Project\Invoke.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Project\Transaction.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Project\Swap.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\logSetting.yaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Config\Project\Swap-Burning.yaml">
		  <SubType>Code</SubType>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="6.2.0" />
		<PackageReference Include="AWSSDK.Core" Version="3.7.3.5" />
		<PackageReference Include="Nethereum.ABI" Version="4.0.5" />
		<PackageReference Include="Nethereum.JsonRpc.WebSocketClient" Version="4.0.5" />
		<PackageReference Include="Nethereum.RPC.Reactive" Version="4.0.5" />
		<PackageReference Include="Nethereum.Rsk" Version="4.0.5" />
		<PackageReference Include="Nethereum.Signer" Version="4.0.5" />
		<PackageReference Include="Nethereum.Util" Version="4.0.5" />
		<PackageReference Include="Nethereum.Web3" Version="4.0.5" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="4.1.2" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="3.2.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="StreamJsonRpc" Version="2.8.21" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
		<PackageReference Include="NetEscapades.Configuration.Yaml" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Config\Event\" />
	</ItemGroup>

</Project>
