# 项目启用开关
Enabled : true

# 项目名称(每个项目必填 格式: 链-模式-币名字)
Name : "XX-BurningSwap-项目"

# 模式 (调用燃烧模式)
Model : "Burning"

# 路由器
SwapRouter : "0x9aE8082DC884BE36d2e92976aCD348Ce647DE99A" 

# 参与的机器人项目组(Main/SoHa)
AccountGroups :
  - "Main"

# 燃烧配置
Burning :
  # Action
  Action : "Swap"
  # 调用数据
  Swap :
    # 购买花费
    AmountIn : 10
    # 最低购买量
    AmountOutMin : 0
    Path :
      - "0x55d398326f99059fF775485246999027B3197955"  # 使用这个币去交换
      - "0x201bC9F242f74C47Bbd898a5DC99cDCD81A21943"  # 获得这个币
    # gas价格
    GasPrice : 
      - 5
    # gas数量
    GasCount : 500000
  # 开始时间 Unix时间戳
  StartTime : 1630857540
  # 开始区块 会自动提前一个
  # StartBlock : 10593690
  # 持续时间 秒
  Duration : 99999999  
  Delay :
    # 间隔 毫秒为单位 (1000 / 间隔 = 每秒次数)
    TimeDelay : 5000
    # 区块延迟 按照购买时的区块向后推迟 N 区块
    # BlockDelay : 0

# 买到了就自动授权
Approve : 
  Enabled : false
  # 授权目标合约 默认:路由器
  # Spender : "0x10ed43c718714eb63d5aa57b78b54704e256024e"
  # 授权数量 默认:最大值
  # Value : "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

# 自动出售
Sell :
  # 开关
  Enabled : false
  # 卖出时得到的币
  Receive : "0x55d398326f99059ff775485246999027b3197955"
  # gas价格 (不写则为跟踪模式)
  # GasPrice : 5
  # 卖出的数量 不写就是全卖
  # AmountIn : 1
  AmountOutMin : 40000
  Delay :
    # 延迟时间 推荐 区块数量 减少检测频率
    TimeDelay : 2
    # 区块延迟 按照购买时的区块向后推迟 N 区块
    BlockDelay : 1