# 项目启用开关
Enabled : true
# 项目名称(每个项目必填 格式: 链-币名字)
Name : "指定代币转账监控"
# 项目模式(地址监控)
Model : "tokenmonitor"
#监控的代币
  Tokens :
   -  Contract : "0x55d398326f99059ff775485246999027b3197955" # USDT
      Amount : "1"
   -  Contract : "0xe9e7cea3dedca5984780bafc599bd69add087d56" # BUSD
      Amount : "1"
   -  Contract : "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c" # WBNB
      Amount : "1"