# 项目启用开关
Enabled: false

# 项目名称(每个项目必填 格式: 链-币名字)
Name: "EVM调用监控项目"

# 项目模式(地址监控)
Model: "Transaction"          # ← 修正拼写

# 监听的调用者
Sender: "0x52bf55fff7af61d7e49c9dbfa72d3498a4a317ab"

# 目标合约（你要发交易到这里）
Contract: "0xe540980f909873370bbe9c19db7c3b5ba4def701"

AccountGroups:
  - "Main"

# 新增：主动调用用的参数（最关键）
Invoke:
  GasCount: 100000     # gas数量
  Data: "0x000"        # 你的完整 calldata（MethodID+ABI参数）
